# t =1, s = 3
version: '3.8'

services:
  tss: &node
    image: tss
    ports:
      - "18000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ROCKET_PORT=8000

  tss2:
    <<: *node
    ports:
      - "28000:8000"

  tss3:
    <<: *node
    ports:
      - "38000:8000"

  manager:
    <<: *node
    container_name: manager
    ports:
      - "9000:9000"
    environment:
      - ROCKET_ENV=release
      - ROCKET_PORT=9000
      - ROCKET_ADDRESS=0.0.0.0